### ISSUE TITLE
[ED-MED] Submission Form - scope/definition of "evaluation tools"

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-evaluation-tools-list#102]
1. Add definition of "evaluation tools" in the intro section of this page -- "Web accessibility evaluation tools are software programs or online services specifically designed to help determine if web content and software meets accessibility standards"
2. Change "These tools will help determine if digital content meet accessibility guidelines" to "These tools **are specifically designed to** help determine if digital content meet accessibility guidelines"
3. Change "Tools, applications or extensions that support the evaluation of digital accessibility" to "Tools, applications or extensions that **are specifically designed to** support the evaluation of digital accessibility"

Rationale: this sets clearer boundaries upfront, and avoids lengthier discussions and sometimes disappointment downstream.

Note: I don't feel particularly strongly about the particular wording "specifically designed to" but strongly encourage clarifying the boundaries beyond merely "that support" or "help determine" (for the sanity of whoever will be processing the submissions).

**Comment by iadawn** [comment]
1. A definition of evaluation tools is included on the listing page. What is the argument for including this on the submission page as well?
2. (and 3) There is more information within the section 'What evaluation tools are included'. Given this content do you still feel that the additional text is needed? Note, that the section on scope was discussed in EO on [27 Jan 2023](https://www.w3.org/2023/01/27-eo-minutes#t01)

**Comment by nitedog** [comment]
On point 2, my editorial suggestions include tweaks for the "What evaluation tools are included", and I agree that this is a very important section to have. My suggestion is to strengthen the wording in this and other sections to avoid confusion.

The rationale is that in the past, I recall often receiving submissions that are out of scope. Sometimes it was easy to explain to submitters why their submissions were out of scope, but others seemed not easy to convince. This is just a friendly suggestion from personal experience, for the sanity of WAI staffers and others who might be maintaining this list. Feel free to drop this if you're not convinced of these light edits, it's nothing I feel strongly about but think it will save you discussions later on.

**Comment by shawna-slh** [comment]
Without commenting on this specific suggestion now, I'm chiming in to say that we need very clear parameters for what is included - and, as much as feasible, to avoid submissions that we will reject.

In the [submission form](https://master--wai-evaluation-tools-list.netlify.app/tools-list/evaluation/submit-a-tool/), "What evaluation tools are included" is intended to address that.

I support additional edits to the list itself and to the submission form that will likely help limit submissions that do not fit.
