### ISSUE TITLE
Under "Tools list" within each card, suggest one more <H4> heading

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-evaluation-tools-list#109]
For each tool listed, the tool name is an `<H3>` and then the following are `<H4>`:

- Features
- Show [More/Less] Details
- Guidelines

However, within the "Show More Details" section there are actually 2 columns - one that lists the applicable guidelines and one that lists more features. Thus, I think this second column (highlighted in the photo) needs an additional heading such as "More Features" to go along with "Guidelines".

<img width="926" alt="Screenshot of result card and proposed missing heading location" src="https://github.com/w3c/wai-evaluation-tools-list/assets/84785057/e603e7e6-05f7-4b83-922b-050eeedaee27">

**Comment by iadawn** [comment]
@VeraLange could we have a chat about this one?

**Comment by iadawn** [comment]
Restructured with 9b03648 

Available for preview at: https://master--wai-evaluation-tools-list.netlify.app/tools-list/evaluation/

**Comment by MicheleAWilliams-A11y** [comment]
Looks great!
