### ISSUE TITLE
Permissions problem with syncing ACT implementation data

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wai-evaluation-tools-list#113]
I set up a GitHub action a couple weeks back to auto-sync ACT implementation data into this repo. That stopped working two weeks ago. From the error it seems to be a permissions problem. Since I can tell that token is still valid, I suspect someone either changed permissions for the bot, or changed permissions in the repo.

Here are the actions log:
https://github.com/w3c/wcag-act-rules/actions/workflows/copy-to-evaluation-tools-list.yml

**Comment by iadawn** [comment]
Am I correct in remembering that @michael-n-cooper set up the permission? Could you double check things please?

**Comment by WilcoFiers** [comment]
I added Michael when I still had admin access to this repo, Michael had to accept the invite.

**Comment by WilcoFiers** [comment]
This has been fixed by @daniel-montalvo. Thanks!
