### ISSUE TITLE
aside ID spaces

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-evaluation-tools-list#121]
_Issue from e-mail_

This may be submitted to a public list.

https://www.w3.org/WAI/tools-list/evaluation/#tools-list

Each tool's info is presented in an ```aside``` element with ID. However, the ID strings contain spaces. For instance:

```<aside class="box" id="Accessibility Suite">```

```<aside class="box" id="axe Accessibility Linter for Visual Studio Code">```

```<aside class="box" id="PDF Accessibility Checker (PAC)">```

The spec says that ID strings cannot contain whitespace characters.

Neither of these calls  will find the second ```aside``` listed above whose id is "axe Accessibility Linter for Visual Studio Code":
```
  document.querySelector("#axe Accessibility Linter for Visual Studio Code");

  document.querySelector("#axe\ Accessibility\ Linter\ for\ Visual\ Studio\ Code")
```

but this will find it:
```
  document.getElementById("axe Accessibility Linter for Visual Studio Code");
```

[Mozilla's MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id) says:
> An id's value must not contain whitespace (spaces, tabs, etc.). Browsers treat non-conforming IDs that contain whitespace as if the whitespace is part of the ID. In contrast to the class attribute, which allows space-separated values, elements can only have one single ID value.
Technically, the value for an id attribute may contain any character, except whitespace characters. However, to avoid inadvertent errors, only ASCII letters, digits, '_', and '-' should be used, and the value for an id attribute should start with a letter.

-- 
Rich Caloggero
Accessibility Specialist
Disability and Access Services
Massachusetts Institute of Technology

**Comment by mhansma96** [comment]
A fix was pushed for this. Not optimal, but functional at least. Should we close this issue?

**Comment by shawna-slh** [comment]
up to you and @iadawn
(I was just the messenger :-)
