### ISSUE TITLE
[ED-LOW ] Error message for tool URL 

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-evaluation-tools-list#122]
Is this an adequate error message? 
In the General Information section, when entering a URL, I put 'www.BestToolEver.com' and got the following error massage:
"Please enter a URL" 
It works fine when I add the http:// 
My question is if there be formatting guidance in the error message or instruction?

**Comment by shawna-slh** [comment]
+1 to providing more specific guidance as feasible.

**Comment by iadawn** [comment]
The error message is generated by the browser so not much can be done about that. I have added some instuctions to include the scheme information.
