### ISSUE TITLE
<legend> as first child

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-evaluation-tools-list#129]
From @daniel-montalvo:

> `legend` needs to be the first child of `fieldset` for this to work
> https://html.spec.whatwg.org/multipage/form-elements.html#the-legend-element
> I'd thought browsers would be more forgivable with this but it seems not

**Comment by mhansma96** [comment]
Where is this a problem? And what does it break by not having it that way?

**Comment by iadawn** [comment]
For example, https://github.com/w3c/wai-evaluation-tools-list/blob/08501fd057e56bd27139d88a58e35b50b2fa44d8/content/submit-a-tool.md?plain=1#L137

```html
 <fieldset class="field" id="purpose">
      <div class="fieldheader">
        <legend class="label-input">Purpose<span class="short-sub">(Required)</span></legend>
      </div>
      <p>What type of evaluations does this tool support?</p>
```

It results in the legend playing less nicely with screen readers. @daniel-montalvo may have more specfics.

**Comment by daniel-montalvo** [comment]
Hi @mhansma96 

Thanks for your work on this.

If the `legend` is not the first child of the `fieldset`, the screen readers do not read the contents of the `legend` as the user tabs through the form controls.

The [HTML spec ](https://html.spec.whatwg.org/multipage/form-elements.html#the-legend-element) requires that the `legend` element be the first child of the `fieldset` element.
Now this works as expected.

**Comment by mhansma96** [comment]
Hi @daniel-montalvo 
Thanks for the quick response and input! Good to hear that it works now.
