### ISSUE TITLE
"Desktop application" type missing

### ISSUE THREAD

**Issue by AndyAtTV** [w3c/wai-evaluation-tools-list#138]
On the Submit a Tool form, in the [Type of tool](https://www.w3.org/WAI/test-evaluate/tools/submit-a-tool/#type) section it mentions "desktop application" as a type, but there's no option to select this. 

Is this a mistake, or are desktop applications supposed to select some other option?

**Comment by mhansma96** [comment]
Good spot. I believe there have been some iterations lately over the names of some filter/submission options so the option "desktop application" has been removed/changed. I added a commit that used another option as an example in the explanation text. It should be live soon.

**Comment by iadawn** [comment]
This was inadvertently removed when removing Desktop App as a valid option as a product to be evaluated. Added back in with [09819c3](https://github.com/w3c/wai-evaluation-tools-list/commit/09819c39c55a8dc7be2204c0bcd48a250cea55f6)
