### ISSUE TITLE
ACT Link broken for IBM Equal Access A11y Checker

### ISSUE THREAD

**Issue by lbeaze** [w3c/wai-evaluation-tools-list#169]
On the [draft list page](https://www.w3.org/WAI/test-evaluate/tools/list/) the ACT url is:

https://www.w3.org/WAI/standards-guidelines/act/implementations/https://www.w3.org/WAI/standards-guidelines/act/implementations/equal-access/

Easy to fix manually if you know what to look for, but we should fix the code to prevent the root URL from being pre-pended.  

Note - this [might be related to issue 170](https://github.com/w3c/wai-evaluation-tools-list/issues/170).

**Comment by iadawn** [comment]
Fixed with #175
