### ISSUE TITLE
ACT links appear for products without ACT test results 

### ISSUE THREAD

**Issue by lbeaze** [w3c/wai-evaluation-tools-list#170]
All products in the [draft list](https://www.w3.org/WAI/test-evaluate/tools/list/) have an ACT Rules implemented link (after **Show more features** is activated). 

Only one product listing has a real [implementation test](https://www.w3.org/WAI/standards-guidelines/act/implementations/equal-access/). 

All others have the following URL in the link:
https://www.w3.org/WAI/standards-guidelines/act/implementations/https://www.w3.org/WAI/standards-guidelines/act/implementations/

If a product doesn't have an implementation test, I recommend we suppress the link - or show that one doesn't exist for the product, yet. 

What was the original intent? 

Note - this [might be related to issue 169](https://github.com/w3c/wai-evaluation-tools-list/issues/169).

**Comment by iadawn** [comment]
Fixed with #175
