### ISSUE TITLE
[high] check ACT Rules links for all

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-evaluation-tools-list#174]
e.g., IBM Equal Access Accessibility Checker (Chrome, Firefox, Edge extension) has:
```<a href="https://www.w3.org/WAI/standards-guidelines/act/implementations/https://www.w3.org/WAI/standards-guidelines/act/implementations/equal-access/" target="_blank">ACT Rules implemented</a>:```

**Comment by iadawn** [comment]
Duplicate of #169
