### ISSUE TITLE
[ED-MED] delete colon after ACT Rules implemented

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-evaluation-tools-list#176]
The colon after ACT Rules implemented makes it look like there should be something after it, so it looks like an error
![image](https://github.com/w3c/wai-evaluation-tools-list/assets/6991814/4b02955f-9160-4095-890a-0f3ebf449511)

**Comment by iadawn** [comment]
There should be something after it that was missing. The missing bit has been put back in so the colon now makes sense. If you disagree, please do reopen
