### ISSUE TITLE
[HIGH] update companion Selecting Web Accessibility Evaluation Tools

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-evaluation-tools-list#179]
[Selecting Web Accessibility Evaluation Tools](https://deploy-preview-32--wai-selecting-eval-tools.netlify.app/test-evaluate/tools/selecting/) needs to be updated at the same time the new Eval Tools List is published.

**Comment by iadawn** [comment]
https://github.com/w3c/wai-selecting-eval-tools/pull/32 addresses this issue
