### ISSUE TITLE
[Submission form] [High] Tooltips don't have right semantics

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-evaluation-tools-list#24]
"Submission form" > "2/3
Tool functionality" > "Guidelines"

Some listed guidelines have a tooltip. SRs announce it as "Info [Name of guideline] graphic"

If I put screen reader focus on that graphic and press Enter, I can get to the info. But that's not right semantics.

The group seems OK with these tooltips as long as they are accessible, although further UX issues were discussed.

- Should we have an expand/collapse button there?
- Should we associate the tooltip to the label with some ARIA?

**Comment by mhansma96** [comment]
We're looking for the right semantics. Do you think adding the actual info on the aria of the icon would be a good solution?

**Comment by daniel-montalvo** [comment]
Thanks @mhansma96 
Yes, similarly to what the course list has.

**Comment by mhansma96** [comment]
We've added the tooltip information to the alt on the img of the tooltip icon. Is this sufficient?
