### ISSUE TITLE
[Submission form] Unclear wording -- Brackets not needed?

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-evaluation-tools-list#25]
Info for the "accessibility statement" URL field says:

> While an accessibility statement is not required to submit a tool, it provides valuable information on your commitment to accessibility to your (potential) users. Get started by visiting Developing an Accessibility Statement.

"(potential)" is in brackets. I think these are not needed. If we want to emphasize "potential", we can use bold, italics, or any other, but brackets seem weird to me.

**Comment by VeraLange** [comment]
The reason "potential" is put in brackets is the distinction between both potential and current users. It's not to emphasize "potential", but rather to show the benefits for both kinds of users.

Would you still remove the brackets in that case?

**Comment by daniel-montalvo** [comment]
Thanks @VeraLange 

It's still weird to me, but I don't feel strongly. Why don't we say "valuable information on your commitment to accessibility to your current and potential users"? Or even simpler, "to your users"?

**Comment by VeraLange** [comment]
We removed "(potential)" for more clarity. :)
