### ISSUE TITLE
Please QA tools list

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-evaluation-tools-list#256]
Hi @josehilera @lbeaze @iadawn 
sorry I lost the actions assigned to me to publish.
Done now.

Please QA the list. e.g., there are 2 listings for Accessibility Cloud.
Thanks!

**Comment by shawna-slh** [comment]
Hi @josehilera @iadawn Can you figure out how to delete the older entry for Accessibility Cloud?

If not, @iadawn let's ask one of our WAI tech folks to help.

**Comment by iadawn** [comment]
Duplicate was https://github.com/w3c/wai-evaluation-tools-list/blob/080da83b3068c0e4c0ea84e0a14484c4075826ff/_data/wai-evaluation-tools-list/submissions/e7d446e0-95d7-11ee-a43c-2fcf67bd5007.json#L41

Removed with f243458
