### ISSUE TITLE
Feedback on Evaluation Tools list

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wai-evaluation-tools-list#40]
Since I don't have permissions to fill out this survey (https://www.w3.org/2002/09/wbs/35532/EvaluationTools_Monkey/results), I'm opening this issue instead.

## On the tool itself

There are no examples of what the ACT inclusion will look like. I would like for the ACT Task Force to have an opportunity to review this before the content is published. A couple of thoughts I did have though:

I think the number of implemented rules and proposed rules should be in the list, in a similar way to how the ACT implementation overview is using this; see https://www.w3.org/WAI/standards-guidelines/act/implementations/#automated-test-tools Leaving the numbers out I feel sends the wrong message. Visitors might think implementing ACT is a "boolean" thing, either a tool supports it, or they don't. It hides how much useful information there really is, and that supports differs significantly between tools. Adding the numbers in I feel encourages people to click through to learn more, whereas if we don't I'm concerned people just aren't going to be all that interested.

On the accessibility statement filter, it seems this filter is going to encourage organisations to create accessibility statement for tools that really don't need one, just so they don't get filtered out the list. APIs for example do not have a user interface. There is nothing to declare in an accessibility statement about them. It would seem appropriate to allow organisations to declare that an accessibility statement is not applicable, and to not have those tools filtered out by the Accessibility statement filter.

On the "standards" filter. It seems like EN 301 549 should be on that list. It has additional requirements to WCAG 2.1. It's different enough that it could be on the list. I'm less convinced that RGAA and BITV should be there. Those are test methodologies, similar to for example Trusted Tester. They test WCAG, they aren't standards in and of themselves.

## On the submission form

The form it offers a field for ACT Rules, which can be any URL. I'm concerned that people may start putting in URLs to their own pages, rather than to W3C reports. I think that sort of defeats the purpose of what we're trying to do by bringing all this information together in one place if organisations start publishing their own ACT support tables, we could lose all oversight that way.

The ACT field also seems wrapped in the output section. This looks like a missing end tag of sorts. I assume that can be fixed easilly.

**Comment by shawna-slh** [comment]
Thank you for the review and input @wilco !

Please create separate issues for each comment (or group of dependent/related comments)

**Comment by shawna-slh** [comment]
Hey @WilcoFiers 
Yesterday and again this morning the EOWG Chairs (@kakinney @bakkenb) were trying to sort through your comments and prepare them for EOWG discussion. We ran out of time trying to figure out what you are proposing. When you put each point in a separate issue, it would be most helpful if you could make more clear what you propose. Here is the [guidance for commenting](https://www.w3.org/WAI/EO/wiki/EOWG_Participation_Info#Comments) that we have for all EOWG participants.

**Comment by WilcoFiers** [comment]
@shawna-slh I'm going to e-mail the chairs directly asking for a chance to meet on the subject.

**Comment by WilcoFiers** [comment]
For comments that haven't been resolved yet, I created separate issues. I'm closing this, since there's nothing left in this issue that isn't covered by other issues:

https://github.com/w3c/wai-evaluation-tools-list/pull/75
https://github.com/w3c/wai-evaluation-tools-list/issues/76
https://github.com/w3c/wai-evaluation-tools-list/issues/77
https://github.com/w3c/wai-evaluation-tools-list/issues/78
