### ISSUE TITLE
[Course List] Not tangential content

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-evaluation-tools-list#45]
Each course item is presented in an `<aside>`. I am not sure that this could be classed as 'tangential content' though. Not 100% on other container options.

* This is a list of evaluation tools - should it be a `<li>`.
* `<section>` is another possibility but it may be that that is too broad for this specific use.

**Comment by carlosapaduarte** [comment]
+1 to having courses as `<li>` inside an `<ol>`, instead of `<aside>` inside a `<div>`

**Comment by mhansma96** [comment]
All boxes that contain content, items or texts seem to have come from the box.html element: https://wai-website-theme.netlify.app/components/boxes/

I think it makes sense to use the WAI component for this to stay in line with the structure and probably more importantly, the lay-out and style
