### ISSUE TITLE
[Course List] Inconsistent presentation of summary information

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-evaluation-tools-list#47]
![Summary information including type of tool, cost and language](https://user-images.githubusercontent.com/2444840/189330074-9664b559-1fa9-45bd-98ce-9a00aca5081d.png)

Type of tool is spelled out which doesn't align with the other items. Also, the icon for type of tool has 'type of tool' as alternative text. This means it will be repeated unnecessarily for some users. Might be worth removing the visible text and just keeping the icon.

**Comment by carlosapaduarte** [comment]
This also applies to information that is hidden by the "Show more details" summary. If you believe the images are able to convey the meaning, then remove the text. Otherwise, hide the images from AT.

**Comment by VeraLange** [comment]
The visible text has been removed, icons have been kept with alt-text.
