### ISSUE TITLE
[Course List] Type of tool icon

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-evaluation-tools-list#48]
![Type of tool icon looks like a plug](https://user-images.githubusercontent.com/2444840/189331289-4ae2899d-a1d7-4bd7-8bcf-8bfdbe5d1cae.png)

The type of tool icon looks like a plug. Not sure this is the best choice. Is there an option to have something like the crossed hammer and spanner:

🛠

?

**Comment by shawna-slh** [comment]
+1
see video

**Comment by VeraLange** [comment]
The title of this issue is confusing, since I think it relates to the Tools list?

The type of tool icon has been changed to resemble a wrench.
