### ISSUE TITLE
[Course list] Search bar

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-evaluation-tools-list#58]
The search bar is coded as 

`<label for="search" aria-label="Search tools, eg. “contrast” or “WCAG”" class="visuallyhidden">Search tools, eg. “contrast” or “WCAG”</label>`

The `<label>` element is not allowed to have an `<aria-label>` attribute, with the accessible name coming from its content.

**Comment by MicheleAWilliams-A11y** [comment]
Additionally, the label for an input should not be placeholder text (which has low color contrast and disappears which impacts people with memory issues). The label should contain either be the word "Search" (which remains persistent on the page and is not hidden from view), the common magnifying glass icon (with alt text "Search" as the label), or contain a "Search" button and a hidden label for the input. See the WAI guide for more: https://www.w3.org/WAI/tutorials/forms/labels/
