### ISSUE TITLE
[Filters] Tool numbers in filter options

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-evaluation-tools-list#59]
The tool number (between parentheses) for most filter options stays at zero. I suppose this is due to the information stored for the tools currently being incomplete. However, it will cause a poor experience for users of the list, because I do not expect them to have this knowledge. 

If we don't display filters until we have the data, then tool providers won't be motivated to update the information, so I won't suggest to leave the filters out. But perhaps we should have a note stating that filters are at zero because tool information needs updating?

**Comment by bakkenb** [comment]
Personally, to me when I see "(0)" it intuitively means that there are no tools with that filter and if I select it I will have no tools show up.
