### ISSUE TITLE
[Course List] (minor) Extensive use of headers

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-evaluation-tools-list#61]
Each course in the list is presented inside an `<aside>` that starts with an `<header>` element

As per the HTML spec:

>The [header](https://html.spec.whatwg.org/multipage/sections.html#the-header-element) element [represents](https://html.spec.whatwg.org/multipage/dom.html#represents) a group of introductory or navigational aids.
>
>A [header](https://html.spec.whatwg.org/multipage/sections.html#the-header-element) element is intended to usually contain a heading (an [h1](https://html.spec.whatwg.org/multipage/sections.html#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements)–[h6](https://html.spec.whatwg.org/multipage/sections.html#the-h1,-h2,-h3,-h4,-h5,-and-h6-elements) element or an [hgroup](https://html.spec.whatwg.org/multipage/sections.html#the-hgroup-element) element), but this is not required. The [header](https://html.spec.whatwg.org/multipage/sections.html#the-header-element) element can also be used to wrap a section's table of contents, a search form, or any relevant logos.

The header in this instance is grouping an heading/link to the tool, the name of the provider and the date when the tool was last updated. 

I do not find this is the proper semantic use for an header, but I don't feel too strongly about it.

**Comment by mhansma96** [comment]
Every list item now has a H3 item in the header like in the stated spec. The rest of the structure is based on: https://wai-website-theme.netlify.app/components/boxes/
