### ISSUE TITLE
[Submission form] Scope of Browser field

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-evaluation-tools-list#63]
As I was filling the form with information about a specific tool, I was unsure about the scope of this form field. The tool can be used as an online tool and a browser plugin, which I checked in the Type of Tool form field. When I got to the browser form field, I was unsure whether the question applied to the online tool (and then I would check all the browsers) or the browser plugin (and then I would check just the single browser the plugin is available for). Given that the outcome if very different in this instance, a note clarifying the scope would be useful. 

Probably, this also applies to the filter list.

**Comment by VeraLange** [comment]
In that case, would it be more useful to upload the two as separate entries (one for the online tool version, and one of the browser plugin)? And thus the form facilitating in making that choice?

**Comment by mhansma96** [comment]
@carlosapaduarte Does this still need to addressed? And what would be the best approach if so? (See previous comment by Vera)

**Comment by carlosapaduarte** [comment]
Sorry, but I missed Vera's comments. 
I like Vera's suggestion of being able to provide information for the two use cases of my tool. Perhaps it could be dependent on the choice made in Type of Tool field. But this might start to be too complex. A note clarifying what is the scope might be enough. Something like "Check all that apply to the different types of tool reported" (if this is what is expected)

**Comment by mhansma96** [comment]
Changes have been implemented. Thanks!
