### ISSUE TITLE
[Submission form] Which email are you asking?

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-evaluation-tools-list#67]
Email address is required but I would want to know what it's for and how it's used. Are you asking who is submitting the information or who can be reached in case of questions? Also, will this be displayed when my tool is uploaded or is it just for WAI to correspond to me?

I would add an "i" information icon and explain email a bit more.

**Comment by VeraLange** [comment]
A short description has been added to inform users about the use of the e-mail address.
