### ISSUE TITLE
[submission form] ACT Rules tweaks

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-evaluation-tools-list#73]
* [x] Update text to better explain what ACT Rules are, and what submitters might want to do about them. Maybe point to the announcement e-mail, hopefully coming this week. @WilcoFiers

* [x] _[update: not needed since it will be in the draft list]_ Add note that we will add a filter for ACT Rules implementation report provided, so users will be able to select which tools provide a report.

* [x] If keeping requirement that implementation report has to be on WAI website, then this can be the start of the field (label? data?): ```https://www.w3.org/WAI/standards-guidelines/act/implementations/```
and submitters just fill in the last bit of the URI

**Comment by EricVelleman** [comment]
To clarify that the URL should be to the ACT reports page on the W3 website, we could change the text under the edit field in the submission form from “For more information, read ACT Rules Implementation in Test Tools and Methodologies.” to “The report needs to be available on the ACT Rules Implementation in Test Tools and Methodologies](https://www.w3.org/WAI/standards-guidelines/act/implementations/) page.”

**Comment by VeraLange** [comment]
Keeping this issue open for now, using your input when adding ACT Rules to the tools page in upcoming version.

**Comment by iadawn** [comment]
I updated the text following various discussions with EO.

@WilcoFiers if you feel there are still issues, please reopen this issue and we can discuss.
