### ISSUE TITLE
Update how ACT reports are listed

### ISSUE THREAD

**Issue by WilcoFiers** [w3c/wai-evaluation-tools-list#77]
I think instead of simply listing to the ACT report, it would be great if the evaluation tools list could provide some information on each implementation. I did a little prototyping, and here's what I think this should look like:

![Screenshot prototyped ACT implementation listing](https://user-images.githubusercontent.com/530687/195076864-85939eb3-ae28-4c85-af71-be45d8efc6f6.png)

1. Change the icon to be the same one used on the ACT implementations page. If preferred, a grey version could be used here, but I think we should keep these icons the same.
2. Add an "ACT Rules Implemented" link, which goes to the implementation report (example: https://www.w3.org/WAI/standards-guidelines/act/implementations/axe-devtools-pro/)
3. Add a small "About ACT" link, to go to https://www.w3.org/WAI/standards-guidelines/act/rules/about/
4. On a new line, add "XX Rules", giving the number of W3C approved rules implemented
5. In small, add "/ XX Proposed Rules", giving the number of ACT TF proposed rules implemented

Here's the HTML for it:

```html
<div class="colRow">
  <img src="https://w3.org/WAI/content-assets/wcag-act-rules/bar-chart-fill.svg" alt="ACT Rules">
  <p>
    <a href="https://www.w3.org/WAI/standards-guidelines/act/implementations/axe-devtools-pro/">ACT Rules Implemented</a>:
    <small>(<a href="https://www.w3.org/WAI/standards-guidelines/act/rules/about/">About ACT</a>)</small><br>
    15 Rules <small>/ 12 Proposed Rules</small>
  </p>
</div>
```

The number of approved / proposed rules implemented is not available in this repo, but it's there when the website is built. You can see how ACT TF did it in the wcag-act-repo, here:
https://github.com/w3c/wcag-act-rules/blob/main/_layouts/act_implementation.html#L7
https://github.com/w3c/wcag-act-rules/blob/main/_layouts/act_implementation.html#L74

To get the implementor, you'll need the `implementor_key`. This is the unique part of the implementation report URL. So for https://www.w3.org/WAI/standards-guidelines/act/implementations/alfa/, the `unique_key` is `alfa`.

**Comment by bakkenb** [comment]
I agree these would be good additions to the details section. Will the second line, rules and proposed rules numbers, be something easy to pull in an automated way or will this have to be manually entered by the submitter or reviewers?

**Comment by WilcoFiers** [comment]
@bakkenb This can be done automatically. Unfortunately it won't work on Netlify though. The Netlify build doesn't have access to the ACT implementor data, but when the WAI site itself is built the data will be there.

I left some info at the bottom of my post on how to do it, for whoever's going to take this on. It's fairly straight-forward.

**Comment by shawna-slh** [comment]
< WAI website hat on > We will address the technical aspect of this in a couple weeks. In the meantime, it's best not to spend any effort on implementation or UI.

**Comment by EricVelleman** [comment]
This proposal seems different from the minutes of the meeting about how to include the ACT rules into the results of the Accessibility Tools page. Earlier decisions by the WG and also the HAN user research concluded that adding numbers that are by itself not understandable confuse users. This is the reason the WG chose for a link to the URL with the report.

**Comment by WilcoFiers** [comment]
Thanks Eric, I appreciate the reasoning behind not showing the numbers, but I think without the numbers, the link to the report and the filter don't make sense.

The use case to support here is to allow people to use ACT consistency (along with other criteria) in their selection process for evaluation tools. Without the numbers, that's not really doable. Only knowing whether or not there is a ACT implementation report does not provide enough information, and we can't exactly expect people to open 5 new pages to get the numbers they need.

ACT TF put a lot of effort into figuring out a way to summarise an implementation. Those two Rules / Proposed Rules numbers are what we came up with, and is what was agreed on with AGWG. This is how ACT TF links to its own implementation reports. Linking to ACT Implementation reports should be consistent across the WAI website.

I understand that these numbers aren't immediately obvious to people who aren't familiar with ACT. Although in fairness, the metrics I'm proposing here are newer than what was used in the user research. This is a little speculative. If I recall, the numbers were also not behind a "See more details" button when the user research is done. These two changes may have solved most of the problem. Even if it didn't, I don't think the right answer is to solve one problem by creating two new ones.

**Comment by mhansma96** [comment]
@WilcoFiers I made some changes to make the ACT filters and data visible again and it can be found on the live preview. Apologies, some ACT related stuff is a bit devided between issues so for now they're open, but we'll close them accordingly when we make further reviews and tweaks. 

When it comes to the listing, we used the HTML and example from this issue, but the only thing missing now is the actual numbers if we want to display them. The question is: how do we get those just from that link? Where is the connection between the resources? 
In the HTML example, those two values are also hard-coded, maybe we can further discuss or you can provide us with some guidance of possible?

**Comment by iadawn** [comment]
@WilcoFiers Regarding point 4 and 5, I am concerned that adding in those numbers will add additional stress to an already fragile website. Can we add this as a future development option?

**Comment by WilcoFiers** [comment]
After some discussion we agreed on copying the implementation data over from the ACT repo so that we don't have to rely on build-time magic. I've made the necessary changed here: https://github.com/w3c/wai-evaluation-tools-list/pull/98, https://github.com/w3c/wcag-act-rules/pull/212, https://github.com/w3c/wcag-act-rules/pull/214

Data is synced using the `michael-m-cooper-bot` account (so please don't delete permissions from it). Data is updated weekly on Monday at midnight. There's also a manual trigger set up here: https://github.com/w3c/wcag-act-rules/actions/workflows/copy-to-evaluation-tools-list.yml (The "Run workflow" button)

This ticket can be closed.

**Comment by iadawn** [comment]
Thanks Wilco, could you note the info about the bot account in a Readme somewhere? Guaranteed I will forget about it so making it easy to find the info will be a big help.
