### ISSUE TITLE
[submission form][med] misc fixes

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-evaluation-tools-list#88]
* [x] fix link: [Back to List of Evaluation Tools](https://www.w3.org/WAI/tools-list/evaluation/list-of-evaluation-tools/)
* [x] footer
* [ ] breadcrumb (add to nav yml)

**Comment by mhansma96** [comment]
I've fixed the dead link, it should be live now.

About the other 2 issues, I am not sure what it means since it seems more about W3C page structure. How can we approach this?  @iadawn Do you have an idea on what to do for this?

**Comment by iadawn** [comment]
@shawna-slh Could you elaborate or pick this up?

**Comment by shawna-slh** [comment]
footer content and format is in the [template](https://raw.githubusercontent.com/w3c/wai-resource-template/main/content/index.md):

```
changelog: /@@/changelog/
acknowledgements: /@@/acknowledgements/  # delete this line if don't have a separate acknowledgements page. And delete it in the footer below.

# NEW: Footer below has several options, and not all will be relevant for specific pages. (Ask Shawn if questions.)

footer: >
   <p><strong>Date:</strong> Updated @@ Month 2021. First published Month 20@@. CHANGELOG.</p>
   <p><strong>Editors:</strong> @@name, @@name. Contributors: @@name, @@name, and <a href="https://www.w3.org/groups/wg/@@wg/participants">participants of the @@WG</a>. ACKNOWLEDGEMENTS lists contributors and credits.</p>
   <p>Developed by the @@ Working Group (<a href="http://www.w3.org/WAI/@@/">@@WG</a>). Developed as part of the <a href="https://www.w3.org/WAI/@@/">WAI-@@ project</a>, @@co-funded by the European Commission.</p>
```

**Comment by shawna-slh** [comment]
breadcrumb will be correct when we publish it and put the page in the navigation.yml

so for now, we can just note for reviewers that they can ignore the breadcrumb. And when we publish, let's remember to do that and check it.

**Comment by shawna-slh** [comment]
Note that for the list itself, We'll want date info something like in the [course list footer](https://www.w3.org/WAI/courses/list/#wai-site-footer):
> Information on specific courses is updated frequently, as we receive it. In the "Details" for each course, there is a date after "This listing was updated on". The Course List user interface was updated on 15 September 2022.

**Comment by iadawn** [comment]
Closing issue if only outstanding item will be addressed on publication
